# Generated by Django 4.1.2 on 2022-11-28 22:17

import app.product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='images/products/default.jpeg', null=True, upload_to=app.product.models.dynamicImagePath),
        ),
    ]
